# Generated by Django 2.2.3 on 2019-08-12 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('video', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='is_playback',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='modified_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 13, 6, 29, 347217)),
        ),
    ]
