# Generated by Django 2.2.3 on 2019-08-12 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190812_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_playback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='modified_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 39, 37, 893369)),
        ),
    ]
