# Generated by Django 2.2.3 on 2019-08-12 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20190812_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='modified_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 58, 21, 903066)),
        ),
    ]
