# Generated by Django 2.2.3 on 2019-08-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190812_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appconfig',
            old_name='subject',
            new_name='email_subject',
        ),
    ]
